import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { data } from "../../data";
import styles from "../../styles/Product.module.css";

function Product({ product }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{product.name.toUpperCase()}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.cardL}>
        {product.images.map((item) => (
          <div key={item.id} className={styles.imgContainer}>
            <Image
              src={item.url}
              width="200"
              height="200"
              objectFit="cover"
              alt=""
            />
          </div>
        ))}
      </div>

      <div className={styles.cardS}>

            <h1 className={styles.title}>{product.name}</h1>
            <p className={styles.description}>{product.description}</p>
            <button className={styles.button}>
              <Link href="/contact">Contact</Link>
            </button>

      </div>


    </div>
  );
}

export default Product;

export const getStaticPaths = async () => {
  const products = data;
  const paths = products.map((product) => {
    return {
      params: {
        name: product.name,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (ctx) => {
  const name = ctx.params.name;
  const product = data.filter((item) => item.name === name)[0];
  return {
    props: {
      product,
    },
  };
};
