import Head from 'next/head'
import Intro from '../components/Intro'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Agency</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <Intro/>
    </div>
  )
}
